thing = "HELLO world HERE is SOME text"
print(thing.lower())
print(thing.upper())
print(thing.isdigit())
locworld = thing.find("world")
print(locworld)
print(thing[::-2])
print("Is palidrome?", thing == thing[::-1])
print(thing.split(' '))
print("Heloo" * 5)